Update deploy_rails.yml

diff --git a/.github/workflows/deploy_rails.yml b/.github/workflows/deploy_rails.yml
--- a/.github/workflows/deploy_rails.yml
+++ b/.github/workflows/deploy_rails.yml
@@ -57,7 +57,7 @@ jobs:
         id: update-task-def
         run: |
           set -e
-          jq '.containerDefinitions[0].image = "\"${{ steps.login-ecr.outputs.registry }}/${{ secrets.AWS_RAILS_REPOSITORY }}:${{ github.sha }}\""' task-def.json > new-task-def.json || { echo "Failed to update task definition"; exit 1; }
+          jq '.containerDefinitions[0].image = "${{ steps.login-ecr.outputs.registry }}/${{ secrets.AWS_RAILS_REPOSITORY }}:${{ github.sha }}"' task-def.json > new-task-def.json || { echo "Failed to update task definition"; exit 1; }
           echo "===== new-task-def.json ====="
           cat new-task-def.json
           
@@ -67,15 +67,17 @@ jobs:
         run: |
           set -e
           jq 'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)' new-task-def.json > update-task-def.json || exit 1
-          # jq '.' update-task-def.json > formatted-task-def.json || exit 1
           echo "===== update-task-def.json ====="
           cat update-task-def.json
+          jq '.' update-task-def.json > formatted-task-def.json || exit 1
+          echo "===== formatted-task-def.json ====="
+          cat formatted-task-def.json
 
       - name: Render new task definition with updated image
         id: task-def
         uses: aws-actions/amazon-ecs-render-task-definition@v1
         with:
-          task-definition: update-task-def.json
+          task-definition: formatted-task-def.json
           container-name: ${{ secrets.AWS_ECS_RAILS_CONTAINER_NAME }}
           image: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ github.sha }}
 
